# Generated by Django 4.0.3 on 2022-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='attach_file',
            field=models.ImageField(blank=True, null=True, upload_to='attach_file/'),
        ),
    ]
