# Generated by Django 4.0 on 2022-06-14 23:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('employer', 'employer'), ('applicant', 'applicant')], max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.basemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_applicant', serialize=False, to='authentication.user')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('house_no', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('working_exp', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('prev_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField()),
                ('age', models.CharField(max_length=2)),
                ('contact', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('tin_number', models.IntegerField()),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Others', 'Others')], max_length=255)),
                ('employed', models.CharField(choices=[('Waged employed', 'Waged employed'), ('Self-employed', 'Self-employed'), ('Others', 'Others')], max_length=255)),
                ('currently_in_school', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('educational_attainment', models.CharField(choices=[('No Formal Education', 'No Formal Education'), ('Elementary Level', 'Elementary Level'), ('Elementary Graduate', 'Elementary Graduate'), ('High School Level', 'High School Level'), ('High School Graduate', 'High School Graduate'), ('College Level', 'College Level'), ('College Graduate', 'College Graduate'), ('Technical-Vocational Graduate', 'Technical-Vocational Graduate'), ('Post-Graduate', 'Post-Graduate')], max_length=255)),
            ],
            bases=('config.basemodel',),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='config.basemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_employer', serialize=False, to='authentication.user')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('business_nature', models.CharField(help_text='Ex. FastFood, IT, BPO', max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('business_permit', models.ImageField(blank=True, null=True, upload_to='business_permit/')),
                ('province', models.CharField(max_length=255)),
                ('tin_number', models.IntegerField()),
                ('employer_type', models.CharField(max_length=255)),
                ('total_workforce', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('barangay', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('telephone_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('fax_number', models.IntegerField()),
            ],
            bases=('config.basemodel',),
        ),
    ]
