# Generated by Django 4.0 on 2022-06-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='barangay',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='employer_type',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='fax_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='province',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='tin_number',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='total_workforce',
        ),
    ]
