# Generated by Django 4.0.3 on 2022-07-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_employer_address_remove_employer_barangay_and_more'),
        ('authentication', '0003_applicant_contact'),
    ]

    operations = [
    ]
